config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  
  # Defines the root path route ("/")
  root "products#index"
  resources :store do
    resources :products
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, Product, user_id: user.id
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store
  belongs_to :user
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :products, dependent: :delete_all
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products, dependent: :delete_all
  has_many :stores, dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_products, only: [:show, :destroy, :edit, :update]
  before_action :set_store, only: [:create, :update, :destroy]
  before_action :authenticate_user!

  def index
    @products = Product.all
  end

  def edit
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(products_params)
    @product.store_id = @store.id
    @product.user_id = current_user.id
    pp @product
    
    if @product.save      
      redirect_to store_products_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    if @product.destroy
      redirect_to store_products_path
    else
      render :show, status: :unprocessable_entity
    end
  end

  def update
    if @product.update(products_params)
      redirect_to store_products_path
    else
      render :edit, status: :unprocessable_entity
    end
  end 

  private
  def set_products
    @product = Product.find(params[:store_id])
  end

  def set_store    
    @store = Product.find(params[:store_id])  
  end

  def products_params
    params.require(:product).permit(:name, :value, :store_id)
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p style='color: green' class='notice'> <%= notice %> </p>
    <p style='color: red' class='alert'> <%= alert %> </p>
    
    <% if user_signed_in? %>
    <%= button_to "Log out", destroy_user_session_path, method: :delete %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, url: store_products_path) do |form| %>
  <div>
    <%= form.text_field :name, placeholder: 'Name' %>
  </div>
  <div>
    <%= form.text_field :value, placeholder: 'Price' %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_form_update.html.erb
<%= form_with(model: product, url: store_product_path) do |form| %>
  <div>
    <%= form.text_field :name, placeholder: 'Name' %>
  </div>
  <div>
    <%= form.text_field :value, placeholder: 'Price' %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id= "<%= dom_id product%>">
  <%= 'Product: '%>
  <p>
    <%= product.name%>
    <%= product.value%>
  </p>
</div>

app/views/products/edit.html.erb
<%= render 'form_update', product: @product %>

app/views/products/index.html.erb
<%= "Hello products of Globant" %>
  <% @products.each do |product|%>  
  <div>
    <%= product.name %>
    <%= product.value %>
    <p> <%= link_to 'Show this product', store_product_path(2 ,product) %> </p>    
  </div>
  <% end %>
<div>
  <%= link_to "New Product", new_store_product_path(1) %>
</div>

app/views/products/new.html.erb
<%= render 'form', product: @product%>

app/views/products/show.html.erb
<%= render @product %>
<div>
  <%= link_to 'Edit product', edit_store_product_path(1, @product) %>
  <%= button_to 'Delete product', store_product_path(1, @product), method: :delete%>
</div>

app/views/store/index.html.erb
<%= "Hello Globant"%>